[project]
#-------
name = "consumer"
version = "0.1.0"
description = ""


# =================-UV-=================

requires-python = ">=3.11, <3.12"

dependencies = [
    "asyncpg>=0.31.0",
    "faststream[nats]>=0.6.5",
    "orjson>=3.11.5",
    "pydantic>=2.12.4",
    "pydantic-settings>=2.12.0",
    "sqlalchemy[asyncio]>=2.0.45",
]

[dependency-groups]
#-----------------
lint = [
    "ruff>=0.14.5",
]


# =================-RUFF-=================

[tool.ruff]
# --------
line-length = 120
indent-width = 4
unsafe-fixes = true
exclude = [
    ".git*",
    ".mypy_cache",
    ".ruff_cache",
    ".venv",
]
output-format = "gitlab"
target-version = "py311"

[tool.ruff.lint]
# -------------
ignore = [
    "EM",  # Заведение отдельной переменной со строкой, для того чтобы добавить ее в Exception не является обязательной практикой
    "FBT",  # boolean аргументы нормально (странное правило)
    "TRY002",  # Чтоб не создавать собственные ошибки
    "TRY003",  # писать message в exception нормально
    "D1", "D203", "D213",  # не имеет смысла принуждать людей писать докстринги без разбора, т.к. это приводит к комментариям вида «капитан очевидность» и ни к чему полезному
    "G004",  # f-строки в логгировании нормальная практика
    "FA",  # мы не поддерживаем и не планируем поддерживать старые версии питона в своих бекендах
    "PLR0913",  # Ограничение на число аргументов функции (5)
    "AIR",
    "RUF001", "RUF003",  # Русские комменты это нормально
    "S608",  #  В AirFlow приходится писать SQL хардкодом
    "PGH003",  # Use specific rule codes when ignoring type issues
    "COM812", "ISC001",  #  несовместимы с ruff format
    "ERA001", # I wanna comment code sometimes
    "S311",
]
fixable = ["ALL"]
unfixable = []
select = ["ALL"]

[tool.ruff.format]
# ---------------
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-format = true

[tool.ruff.lint.isort]
# -------------------
no-lines-before = ["standard-library", "local-folder"]
known-third-party = []
known-local-folder = []
lines-after-imports = 2
